# Generated by Django 5.2.1 on 2025-05-28 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('current_study', models.TextField()),
                ('year12_state', models.CharField(max_length=100)),
                ('year12_completion_year', models.IntegerField()),
                ('current_state', models.CharField(max_length=100)),
                ('atar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('can_commit_3_hours', models.BooleanField()),
                ('can_commit_1_year', models.BooleanField()),
                ('can_tutor_most_weeks', models.BooleanField()),
                ('can_tutor_groups', models.BooleanField()),
                ('subjects_to_tutor', models.TextField()),
                ('has_working_with_children_check', models.BooleanField()),
                ('motivation', models.TextField()),
                ('video_submission', models.FileField(blank=True, null=True, upload_to='applications/videos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='applications/resumes/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('application_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='tutor_applications.tutorapplication')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
