# Generated by Django 5.2.1 on 2025-05-28 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Reviewer's name", max_length=255)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(help_text='The review content')),
                ('platform', models.CharField(choices=[('trustpilot', 'Trustpilot'), ('google', 'Google')], default='trustpilot', help_text='Platform where the review was posted', max_length=20)),
                ('review_date', models.DateField(help_text='Date when the review was posted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this review should be displayed')),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying reviews (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['display_order', '-review_date'],
            },
        ),
    ]
